# Generated by Django 5.0.6 on 2024-05-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestock',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='health_Status',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='weight',
        ),
        migrations.AddField(
            model_name='livestock',
            name='health_status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
