# Generated by Django 5.0.6 on 2024-05-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_remove_livestock_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='breed_image',
            field=models.ImageField(blank=True, upload_to='breed_images/'),
        ),
    ]
