# Generated by Django 5.0.6 on 2024-05-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0006_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='breed_image',
            field=models.ImageField(blank=True, upload_to='breed_img/'),
        ),
    ]
